logging:
  level:
    guru: debug
server:
  port: 9091
sfg:
  brewery:
    beer-service-host: http://localhost:9090
spring:
  application:
    name: order-service
  artemis:
    user: artemis
    password: simetraehcapa
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  zipkin:
    enabled: false
tastingroom:
  enabled: true