logging:
  level:
    guru: debug
server:
  port: 9091
sfg:
  brewery:
    beer-service-host: http://localhost:9090
spring:
  application:
    name: order-service
  artemis:
    host: 192.168.99.101
    user: artemis
    password: simetraehcapa
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true

tastingroom:
  enabled: true